name: cd
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile
      - name: Build renderer
        run: make build packages
      - name: Build Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: false
          args: --universal
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bundle/NTS Desktop-*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
