name: ci
on:
  - push
  - pull_request
jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
      - name: Install dependencies
        run: yarn install --immutable --prefer-offline
      - name: Typecheck
        run: tsc --noEmit
